// Package nginx renders a proxy state into nginx configuration files.
//
// Files are relative to one config directory; nginx resolves relative include, certificate and
// password-file paths against the directory of the main config file, so the same files can be
// validated in a staging directory and then moved into place.
package nginx

import (
	"fmt"
	"regexp"
	"slices"
	"strconv"
	"strings"

	"github.com/supabase-manager/manager/internal/proxy-manager/spec"
)

const (
	// AccessLogDir is where per-host JSON access logs are written inside the container.
	AccessLogDir = "/var/log/nginx/sm"
	httpsSocket  = "unix:/var/run/sm-https.sock"
	acmeSocket   = "unix:/var/run/sm-acme.sock"
)

// Render returns the configuration files for one nginx instance.
func Render(st *spec.State) *spec.Output {
	out := spec.NewOutput()
	r := &renderer{st: st, out: out}
	out.Files["nginx.conf"] = r.mainConf()
	out.Files["upstreams.conf"] = r.upstreams()
	out.Files["streams.conf"] = r.streams()
	for _, h := range st.Hosts {
		out.Files[fmt.Sprintf("hosts/%d.conf", h.ID)] = r.host(h)
	}
	for id, al := range st.AccessLists {
		var b strings.Builder
		for _, u := range al.Users {
			b.WriteString(u.Username + ":" + u.Hash + "\n")
		}
		out.Files[fmt.Sprintf("htpasswd/%d", id)] = b.String()
	}
	for id, c := range st.Certs {
		out.Files[fmt.Sprintf("certs/%d.crt", id)] = c.CertPEM
		key := fmt.Sprintf("certs/%d.key", id)
		out.Files[key] = c.KeyPEM
		out.Secret[key] = true
	}
	return out
}

type renderer struct {
	st  *spec.State
	out *spec.Output
}

func q(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return `"` + s + `"`
}

func (r *renderer) listen(port int) string {
	ip := r.st.Instance.BindIP
	if ip == "" || ip == "0.0.0.0" {
		return strconv.Itoa(port)
	}
	if strings.Contains(ip, ":") {
		return "[" + ip + "]:" + strconv.Itoa(port)
	}
	return ip + ":" + strconv.Itoa(port)
}

// httpsListen is the listen address of TLS servers. With TLS-ALPN-01 enabled, port 443 is
// owned by a stream server that splits ACME challenges from regular traffic, and the TLS
// servers listen on a unix socket with the PROXY protocol carrying the client address.
func (r *renderer) httpsListen(extra string) string {
	if r.st.Instance.TLSALPN {
		return httpsSocket + " ssl proxy_protocol" + extra
	}
	return r.listen(r.st.Instance.HTTPSPort) + " ssl" + extra
}

func (r *renderer) hasHTTPS() bool { return r.st.Instance.HTTPSPort > 0 }

func (r *renderer) mainConf() string {
	in := r.st.Instance
	var b strings.Builder
	b.WriteString("# Generated by Supabase Manager for instance " + q(in.Name) + ". Changes are overwritten on deploy.\n")
	b.WriteString(`worker_processes auto;
pid /var/run/nginx.pid;
error_log /dev/stderr warn;

events {
    worker_connections 4096;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    tcp_nopush on;
    keepalive_timeout 65;
    server_tokens off;
    server_names_hash_bucket_size 128;
    client_max_body_size 16m;
    proxy_buffer_size 16k;
    proxy_buffers 8 16k;
    proxy_busy_buffers_size 32k;

    log_format sm_json escape=json '{"time":"$time_iso8601","host":"$host","remote":"$remote_addr","method":"$request_method","uri":"$request_uri","status":$status,"bytes":$body_bytes_sent,"duration":$request_time,"upstream":"$upstream_addr","upstream_status":"$upstream_status","referer":"$http_referer","ua":"$http_user_agent"}';
    access_log off;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        "" close;
    }

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SMSSL:10m;
    ssl_session_timeout 1d;

    include upstreams.conf;
    include hosts/*.conf;

`)
	if in.HTTPPort > 0 {
		b.WriteString("    server {\n")
		b.WriteString("        listen " + r.listen(in.HTTPPort) + " default_server;\n")
		b.WriteString("        server_name _;\n")
		r.acmeLocation(&b, "        ")
		b.WriteString("        location / {\n            return 404;\n        }\n    }\n")
	}
	if r.hasHTTPS() {
		b.WriteString("\n    server {\n")
		b.WriteString("        listen " + r.httpsListen(" default_server") + ";\n")
		b.WriteString("        server_name _;\n        ssl_reject_handshake on;\n    }\n")
	}
	b.WriteString("}\n\nstream {\n    include streams.conf;\n}\n")
	return b.String()
}

func (r *renderer) acmeLocation(b *strings.Builder, ind string) {
	b.WriteString(ind + "location ^~ /.well-known/acme-challenge/ {\n")
	b.WriteString(ind + "    proxy_pass " + r.st.Instance.ManagerURL + ";\n")
	b.WriteString(ind + "    proxy_set_header Host $host;\n")
	b.WriteString(ind + "}\n")
}

func upstreamName(id uint) string { return fmt.Sprintf("sm_u%d", id) }

func (r *renderer) upstreamBlock(b *strings.Builder, name string, u *spec.Upstream, stream bool) {
	b.WriteString("upstream " + name + " {\n")
	algo := u.Algorithm
	if u.Sticky && algo != spec.AlgoIPHash {
		if !stream {
			r.out.Warn(fmt.Sprintf("upstream %q: nginx has no cookie stickiness, ip_hash is used instead", u.Name))
		}
		algo = spec.AlgoIPHash
	}
	switch algo {
	case spec.AlgoLeastConn:
		b.WriteString("    least_conn;\n")
	case spec.AlgoIPHash:
		if stream {
			b.WriteString("    hash $remote_addr consistent;\n")
		} else {
			b.WriteString("    ip_hash;\n")
		}
	}
	if len(u.Targets) == 0 {
		b.WriteString("    server 127.0.0.1:9 down;\n")
		r.out.Warn(fmt.Sprintf("upstream %q has no reachable targets", u.Name))
	}
	for _, t := range u.Targets {
		addr := t.Host
		if strings.Contains(addr, ":") {
			addr = "[" + addr + "]"
		}
		line := fmt.Sprintf("    server %s:%d", addr, t.Port)
		if t.Weight > 1 {
			line += fmt.Sprintf(" weight=%d", t.Weight)
		}
		if u.Health.Enabled {
			line += " max_fails=3 fail_timeout=10s"
		}
		if t.Backup {
			if algo == spec.AlgoIPHash {
				r.out.Warn(fmt.Sprintf("upstream %q: nginx cannot combine backup targets with IP hashing, %s:%d is used as a regular target", u.Name, t.Host, t.Port))
			} else {
				line += " backup"
			}
		}
		b.WriteString(line + ";\n")
	}
	if !stream {
		b.WriteString("    keepalive 32;\n")
	}
	b.WriteString("}\n\n")
}

func (r *renderer) usedHTTPUpstreams() []uint {
	seen := map[uint]bool{}
	var ids []uint
	add := func(id uint) {
		if id != 0 && !seen[id] && r.st.Upstreams[id] != nil {
			seen[id] = true
			ids = append(ids, id)
		}
	}
	for _, h := range r.st.Hosts {
		add(h.Upstream)
		for _, rt := range h.Routes {
			add(rt.Upstream)
		}
	}
	slices.Sort(ids)
	return ids
}

func (r *renderer) upstreams() string {
	var b strings.Builder
	b.WriteString("# Upstreams (generated)\n\n")
	for _, id := range r.usedHTTPUpstreams() {
		r.upstreamBlock(&b, upstreamName(id), r.st.Upstreams[id], false)
	}
	return b.String()
}

func (r *renderer) streams() string {
	var b strings.Builder
	b.WriteString("# TCP/UDP streams (generated)\n\n")
	done := map[uint]bool{}
	for _, s := range r.st.Streams {
		u := r.st.Upstreams[s.Upstream]
		if u == nil {
			r.out.Warn(fmt.Sprintf("stream on port %d has no upstream and is skipped", s.ListenPort))
			continue
		}
		name := fmt.Sprintf("sm_s%d", s.Upstream)
		if !done[s.Upstream] {
			done[s.Upstream] = true
			r.upstreamBlock(&b, name, u, true)
		}
		b.WriteString("server {\n")
		l := r.listen(s.ListenPort)
		if s.Protocol == "udp" {
			l += " udp"
		}
		b.WriteString("    listen " + l + ";\n")
		b.WriteString("    proxy_pass " + name + ";\n")
		if s.Protocol == "udp" {
			b.WriteString("    proxy_timeout 30s;\n")
		} else {
			b.WriteString("    proxy_connect_timeout 10s;\n    proxy_timeout 1h;\n")
		}
		b.WriteString("}\n\n")
	}
	if r.st.Instance.TLSALPN && r.hasHTTPS() {
		b.WriteString("# Port 443: TLS-ALPN-01 challenges go to the manager, everything else to the TLS servers.\n")
		b.WriteString("map $ssl_preread_alpn_protocols $sm_tls_backend {\n")
		b.WriteString("    ~\\bacme-tls/1\\b " + acmeSocket + ";\n")
		b.WriteString("    default " + httpsSocket + ";\n}\n\n")
		b.WriteString("server {\n    listen " + r.listen(r.st.Instance.HTTPSPort) + ";\n")
		b.WriteString("    ssl_preread on;\n    proxy_protocol on;\n    proxy_pass $sm_tls_backend;\n}\n\n")
		b.WriteString("server {\n    listen " + acmeSocket + " proxy_protocol;\n")
		b.WriteString("    proxy_pass " + r.st.Instance.ALPNSolverAddr + ";\n}\n")
	}
	return b.String()
}

// locationGroup is a set of routes sharing one path match; only the first route's settings
// apply, header matches on the others choose the upstream.
type locationGroup struct {
	pathType, path string
	routes         []spec.Route
}

func groupRoutes(routes []spec.Route) []*locationGroup {
	var groups []*locationGroup
	idx := map[string]*locationGroup{}
	for _, rt := range routes {
		pt := rt.PathType
		if pt == "" {
			pt = spec.PathPrefix
		}
		key := pt + " " + rt.Path
		g := idx[key]
		if g == nil {
			g = &locationGroup{pathType: pt, path: rt.Path}
			idx[key] = g
			groups = append(groups, g)
		}
		g.routes = append(g.routes, rt)
	}
	return groups
}

func (r *renderer) host(h spec.Host) string {
	var b strings.Builder
	label := strings.Join(h.Domains, ", ")
	fmt.Fprintf(&b, "# Host %d: %s (generated)\n\n", h.ID, label)
	if h.RateLimit.Enabled && h.RateLimit.RPS > 0 {
		fmt.Fprintf(&b, "limit_req_zone $binary_remote_addr zone=sm_h%d:10m rate=%dr/s;\n\n", h.ID, h.RateLimit.RPS)
	}
	r.ipGeo(&b, h)
	if h.CORS.Enabled && !slices.Contains(h.CORS.Origins, "*") && len(h.CORS.Origins) > 0 {
		fmt.Fprintf(&b, "map $http_origin $sm_cors_h%d {\n    default \"\";\n", h.ID)
		for _, o := range h.CORS.Origins {
			b.WriteString("    " + q(o) + " $http_origin;\n")
		}
		b.WriteString("}\n\n")
	}

	cert := r.st.Certs[h.CertID]
	tls := cert != nil && r.hasHTTPS()
	if h.CertID != 0 && cert == nil {
		r.out.Warn(fmt.Sprintf("host %s: the certificate is not issued yet, the host is served over HTTP only", label))
	}
	if r.st.Instance.HTTPPort > 0 {
		b.WriteString("server {\n")
		b.WriteString("    listen " + r.listen(r.st.Instance.HTTPPort) + ";\n")
		r.serverCommon(&b, h)
		r.acmeLocation(&b, "    ")
		if tls && h.ForceHTTPS {
			b.WriteString("    location / {\n        return 301 https://$host$request_uri;\n    }\n")
		} else {
			r.serverBody(&b, h, false)
		}
		b.WriteString("}\n")
	}
	if tls {
		b.WriteString("\nserver {\n")
		b.WriteString("    listen " + r.httpsListen("") + ";\n")
		if h.HTTP2 {
			b.WriteString("    http2 on;\n")
		}
		if r.st.Instance.TLSALPN {
			b.WriteString("    set_real_ip_from unix:;\n    real_ip_header proxy_protocol;\n")
		}
		r.serverCommon(&b, h)
		fmt.Fprintf(&b, "    ssl_certificate certs/%d.crt;\n    ssl_certificate_key certs/%d.key;\n", cert.ID, cert.ID)
		r.serverBody(&b, h, true)
		b.WriteString("}\n")
	}
	return b.String()
}

func (r *renderer) serverCommon(b *strings.Builder, h spec.Host) {
	b.WriteString("    server_name " + strings.Join(h.Domains, " ") + ";\n")
	fmt.Fprintf(b, "    access_log %s/%d.log sm_json;\n", AccessLogDir, h.ID)
}

func (r *renderer) serverBody(b *strings.Builder, h spec.Host, tls bool) {
	switch h.Kind {
	case spec.HostRedirect:
		code := h.RedirectCode
		if code == 0 {
			code = 301
		}
		target := h.RedirectURL
		if h.PreservePath {
			target = strings.TrimRight(target, "/") + "$request_uri"
		}
		fmt.Fprintf(b, "    location / {\n        return %d %s;\n    }\n", code, q(target))
		return
	case spec.HostError:
		code := h.ErrorCode
		if code == 0 {
			code = 404
		}
		b.WriteString("    location / {\n        default_type text/html;\n")
		fmt.Fprintf(b, "        return %d %s;\n    }\n", code, q(h.ErrorBody))
		return
	}

	if h.MaxBodyMB < 0 {
		b.WriteString("    client_max_body_size 0;\n")
	} else if h.MaxBodyMB > 0 {
		fmt.Fprintf(b, "    client_max_body_size %dm;\n", h.MaxBodyMB)
	}
	r.accessControl(b, "    ", h.AccessList)
	if h.RateLimit.Enabled && h.RateLimit.RPS > 0 {
		burst := max(h.RateLimit.Burst, 0)
		fmt.Fprintf(b, "    limit_req zone=sm_h%d burst=%d nodelay;\n    limit_req_status 429;\n", h.ID, burst)
	}
	if h.RawNginx != "" {
		b.WriteString("    # Custom configuration\n")
		for line := range strings.SplitSeq(strings.TrimRight(h.RawNginx, "\n"), "\n") {
			b.WriteString("    " + line + "\n")
		}
	}

	groups := groupRoutes(h.Routes)
	hasRoot := false
	for _, g := range groups {
		if g.pathType == spec.PathPrefix && g.path == "/" {
			hasRoot = true
		}
		r.location(b, h, g, tls)
	}
	if !hasRoot {
		r.location(b, h, &locationGroup{pathType: spec.PathPrefix, path: "/"}, tls)
	}
}

// ipGeo maps the client address against the host's IP rules. They are a firewall in front of the
// access list: a deny always wins, and allow rules turn the host into an allowlist.
func (r *renderer) ipGeo(b *strings.Builder, h spec.Host) {
	var allow, deny []string
	for _, ru := range h.IPRules {
		if ru.Action == "deny" {
			deny = append(deny, ru.CIDR)
		} else {
			allow = append(allow, ru.CIDR)
		}
	}
	for _, set := range []struct {
		name  string
		cidrs []string
	}{{"deny", deny}, {"allow", allow}} {
		if len(set.cidrs) == 0 {
			continue
		}
		def, lines := "0", ""
		for _, c := range set.cidrs {
			// geo's default is 0.0.0.0/0, and nginx rejects defining that network twice.
			if c == "0.0.0.0/0" {
				def = "1"
			} else {
				lines += "    " + c + " 1;\n"
			}
		}
		fmt.Fprintf(b, "geo $sm_%s_h%d {\n    default %s;\n%s", set.name, h.ID, def, lines)
		b.WriteString("}\n\n")
	}
}

func (r *renderer) ipCheck(b *strings.Builder, ind string, h spec.Host) {
	var hasAllow, hasDeny bool
	for _, ru := range h.IPRules {
		if ru.Action == "deny" {
			hasDeny = true
		} else {
			hasAllow = true
		}
	}
	if hasDeny {
		fmt.Fprintf(b, "%sif ($sm_deny_h%d) {\n%s    return 403;\n%s}\n", ind, h.ID, ind, ind)
	}
	if hasAllow {
		fmt.Fprintf(b, "%sif ($sm_allow_h%d = 0) {\n%s    return 403;\n%s}\n", ind, h.ID, ind, ind)
	}
}

// accessControl writes an access list's allow/deny rules and basic auth. With both, "satisfy"
// decides whether one or both must pass.
func (r *renderer) accessControl(b *strings.Builder, ind string, aclID uint) {
	al := r.st.AccessLists[aclID]
	var allow, deny []string
	if al != nil {
		allow = append(allow, al.Allow...)
		deny = append(deny, al.Deny...)
	}
	for _, d := range deny {
		b.WriteString(ind + "deny " + d + ";\n")
	}
	for _, a := range allow {
		b.WriteString(ind + "allow " + a + ";\n")
	}
	if len(allow) > 0 {
		b.WriteString(ind + "deny all;\n")
	}
	if al != nil && len(al.Users) > 0 {
		b.WriteString(ind + "auth_basic \"Restricted\";\n")
		fmt.Fprintf(b, "%sauth_basic_user_file htpasswd/%d;\n", ind, al.ID)
		if al.Satisfy == "any" && len(allow) > 0 {
			b.WriteString(ind + "satisfy any;\n")
		}
	}
}

func locationMatch(g *locationGroup) string {
	switch g.pathType {
	case spec.PathExact:
		return "= " + g.path
	case spec.PathRegex:
		return "~ " + q(g.path)
	}
	return g.path
}

var reMeta = regexp.MustCompile(`[.*+?()|\[\]{}^$\\]`)

func (r *renderer) location(b *strings.Builder, h spec.Host, g *locationGroup, tls bool) {
	const ind = "        "
	b.WriteString("    location " + locationMatch(g) + " {\n")
	r.ipCheck(b, ind, h)

	var base spec.Route
	var variants []spec.Route
	found := false
	for _, rt := range g.routes {
		if len(rt.Headers) == 0 && !found {
			base, found = rt, true
			continue
		}
		variants = append(variants, rt)
	}
	if !found && len(variants) > 0 {
		// Only header-matched routes: their settings come from the first one, and requests
		// matching none of them go to the host's default upstream.
		base = variants[0]
		base.Headers = nil
		base.Upstream = 0
	}
	upstreamOf := func(rt spec.Route) uint {
		if rt.Upstream != 0 && r.st.Upstreams[rt.Upstream] != nil {
			return rt.Upstream
		}
		if r.st.Upstreams[h.Upstream] != nil {
			return h.Upstream
		}
		return 0
	}
	baseUp := upstreamOf(base)
	if baseUp == 0 && len(variants) == 0 {
		b.WriteString(ind + "return 502;\n    }\n")
		if len(g.routes) > 0 || h.Upstream == 0 {
			r.out.Warn(fmt.Sprintf("host %s: location %s has no upstream", strings.Join(h.Domains, ", "), g.path))
		}
		return
	}

	if base.AccessList != 0 && r.st.AccessLists[base.AccessList] != nil {
		r.accessControl(b, ind, base.AccessList)
	}

	u := r.st.Upstreams[baseUp]
	scheme := "http"
	if u != nil && u.Scheme == "https" {
		scheme = "https"
	}

	anyTLS := scheme == "https"
	proxyTarget := scheme + "://" + upstreamName(baseUp)
	if len(variants) > 0 {
		def := ""
		if baseUp != 0 {
			def = upstreamName(baseUp)
		}
		b.WriteString(ind + "set $sm_up " + q(def) + ";\n")
		b.WriteString(ind + "set $sm_scheme " + scheme + ";\n")
		for i, v := range variants {
			up := upstreamOf(v)
			if up == 0 {
				continue
			}
			vn := fmt.Sprintf("$sm_m%d", i)
			b.WriteString(ind + "set " + vn + " \"\";\n")
			for _, hm := range v.Headers {
				vr := "$http_" + strings.ReplaceAll(strings.ToLower(hm.Name), "-", "_")
				if strings.HasPrefix(hm.Value, "~") {
					fmt.Fprintf(b, "%sif (%s ~ %s) {\n%s    set %s \"${%s}1\";\n%s}\n", ind, vr, q(hm.Value[1:]), ind, vn, vn[1:], ind)
				} else {
					fmt.Fprintf(b, "%sif (%s = %s) {\n%s    set %s \"${%s}1\";\n%s}\n", ind, vr, q(hm.Value), ind, vn, vn[1:], ind)
				}
			}
			vs := "http"
			if r.st.Upstreams[up].Scheme == "https" {
				vs, anyTLS = "https", true
			}
			fmt.Fprintf(b, "%sif (%s = %s) {\n%s    set $sm_up %s;\n%s    set $sm_scheme %s;\n%s}\n", ind, vn, q(strings.Repeat("1", len(v.Headers))), ind, upstreamName(up), ind, vs, ind)
		}
		if baseUp == 0 {
			b.WriteString(ind + "if ($sm_up = \"\") {\n" + ind + "    return 502;\n" + ind + "}\n")
		}
		proxyTarget = "$sm_scheme://$sm_up"
	}

	if base.StripPrefix && g.pathType == spec.PathPrefix && g.path != "/" {
		p := strings.TrimRight(g.path, "/")
		b.WriteString(ind + "rewrite " + q("^"+reMeta.ReplaceAllString(p, `\$0`)+"/?(.*)$") + " /$1 break;\n")
	}
	if base.RewriteRegex != "" {
		b.WriteString(ind + "rewrite " + q(base.RewriteRegex) + " " + q(base.RewriteReplacement) + " break;\n")
	}

	b.WriteString(ind + "proxy_http_version 1.1;\n")
	b.WriteString(ind + "proxy_set_header Host $host;\n")
	b.WriteString(ind + "proxy_set_header X-Real-IP $remote_addr;\n")
	b.WriteString(ind + "proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
	b.WriteString(ind + "proxy_set_header X-Forwarded-Proto $scheme;\n")
	b.WriteString(ind + "proxy_set_header X-Forwarded-Host $host;\n")
	if h.WebSocket {
		b.WriteString(ind + "proxy_set_header Upgrade $http_upgrade;\n")
		b.WriteString(ind + "proxy_set_header Connection $connection_upgrade;\n")
	} else {
		b.WriteString(ind + "proxy_set_header Connection \"\";\n")
	}
	for _, hd := range append(append([]spec.Header{}, h.RequestHeaders...), base.RequestHeaders...) {
		b.WriteString(ind + "proxy_set_header " + hd.Name + " " + q(hd.Value) + ";\n")
	}
	if h.ConnectTimeout > 0 {
		fmt.Fprintf(b, "%sproxy_connect_timeout %ds;\n", ind, h.ConnectTimeout)
	}
	if h.ReadTimeout > 0 {
		fmt.Fprintf(b, "%sproxy_read_timeout %ds;\n%sproxy_send_timeout %ds;\n", ind, h.ReadTimeout, ind, h.ReadTimeout)
	} else if h.WebSocket {
		b.WriteString(ind + "proxy_read_timeout 1h;\n" + ind + "proxy_send_timeout 1h;\n")
	}
	if anyTLS {
		b.WriteString(ind + "proxy_ssl_server_name on;\n")
	}

	// add_header is not inherited once a level defines its own, so every location carries the
	// host's response headers.
	for _, hd := range append(append([]spec.Header{}, h.ResponseHeaders...), base.ResponseHeaders...) {
		b.WriteString(ind + "add_header " + hd.Name + " " + q(hd.Value) + " always;\n")
	}
	if tls && h.HSTS {
		v := "max-age=31536000"
		if h.HSTSSubdomains {
			v += "; includeSubDomains"
		}
		b.WriteString(ind + "add_header Strict-Transport-Security " + q(v) + " always;\n")
	}
	if h.CORS.Enabled {
		r.cors(b, ind, h)
	}
	b.WriteString(ind + "proxy_pass " + proxyTarget + ";\n")
	b.WriteString("    }\n")
}

func (r *renderer) cors(b *strings.Builder, ind string, h spec.Host) {
	origin := fmt.Sprintf("$sm_cors_h%d", h.ID)
	if slices.Contains(h.CORS.Origins, "*") || len(h.CORS.Origins) == 0 {
		origin = "*"
		if h.CORS.Credentials {
			origin = "$http_origin"
		}
	}
	methods := h.CORS.Methods
	if methods == "" {
		methods = "GET, POST, PUT, PATCH, DELETE, OPTIONS"
	}
	headers := h.CORS.Headers
	if headers == "" {
		headers = "Authorization, Content-Type, apikey, x-client-info"
	}
	b.WriteString(ind + "add_header Access-Control-Allow-Origin " + q(origin) + " always;\n")
	b.WriteString(ind + "add_header Access-Control-Allow-Methods " + q(methods) + " always;\n")
	b.WriteString(ind + "add_header Access-Control-Allow-Headers " + q(headers) + " always;\n")
	if h.CORS.Credentials {
		b.WriteString(ind + "add_header Access-Control-Allow-Credentials \"true\" always;\n")
	}
	if h.CORS.MaxAge > 0 {
		fmt.Fprintf(b, "%sadd_header Access-Control-Max-Age \"%d\" always;\n", ind, h.CORS.MaxAge)
	}
	b.WriteString(ind + "add_header Vary \"Origin\" always;\n")
	b.WriteString(ind + "if ($request_method = OPTIONS) {\n" + ind + "    return 204;\n" + ind + "}\n")
}
