// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: v1/agent.proto

package proxyagentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AgentMessage_Hello
	//	*AgentMessage_Result
	//	*AgentMessage_Status
	//	*AgentMessage_Log
	Msg           isAgentMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetMsg() isAgentMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AgentMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMessage) GetResult() *Result {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *AgentMessage) GetStatus() *Status {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *AgentMessage) GetLog() *LogChunk {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Log); ok {
			return x.Log
		}
	}
	return nil
}

type isAgentMessage_Msg interface {
	isAgentMessage_Msg()
}

type AgentMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentMessage_Result struct {
	Result *Result `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

type AgentMessage_Status struct {
	Status *Status `protobuf:"bytes,3,opt,name=status,proto3,oneof"`
}

type AgentMessage_Log struct {
	Log *LogChunk `protobuf:"bytes,4,opt,name=log,proto3,oneof"`
}

func (*AgentMessage_Hello) isAgentMessage_Msg() {}

func (*AgentMessage_Result) isAgentMessage_Msg() {}

func (*AgentMessage_Status) isAgentMessage_Msg() {}

func (*AgentMessage_Log) isAgentMessage_Msg() {}

type Hello struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	InstanceId uint64                 `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// "nginx" or "traefik".
	Kind         string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	AgentVersion string `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	ProxyVersion string `protobuf:"bytes,4,opt,name=proxy_version,json=proxyVersion,proto3" json:"proxy_version,omitempty"`
	// Checksum of the live configuration; empty when the agent has none yet.
	ConfigChecksum string `protobuf:"bytes,5,opt,name=config_checksum,json=configChecksum,proto3" json:"config_checksum,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetInstanceId() uint64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *Hello) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Hello) GetProxyVersion() string {
	if x != nil {
		return x.ProxyVersion
	}
	return ""
}

func (x *Hello) GetConfigChecksum() string {
	if x != nil {
		return x.ConfigChecksum
	}
	return ""
}

type ManagerMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ManagerMessage_Welcome
	//	*ManagerMessage_Apply
	//	*ManagerMessage_Restart
	//	*ManagerMessage_StartTail
	//	*ManagerMessage_StopTail
	//	*ManagerMessage_Ping
	Msg           isManagerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerMessage) Reset() {
	*x = ManagerMessage{}
	mi := &file_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerMessage) ProtoMessage() {}

func (x *ManagerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerMessage.ProtoReflect.Descriptor instead.
func (*ManagerMessage) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ManagerMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ManagerMessage) GetMsg() isManagerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ManagerMessage) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Msg.(*ManagerMessage_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *ManagerMessage) GetApply() *Apply {
	if x != nil {
		if x, ok := x.Msg.(*ManagerMessage_Apply); ok {
			return x.Apply
		}
	}
	return nil
}

func (x *ManagerMessage) GetRestart() *Restart {
	if x != nil {
		if x, ok := x.Msg.(*ManagerMessage_Restart); ok {
			return x.Restart
		}
	}
	return nil
}

func (x *ManagerMessage) GetStartTail() *StartTail {
	if x != nil {
		if x, ok := x.Msg.(*ManagerMessage_StartTail); ok {
			return x.StartTail
		}
	}
	return nil
}

func (x *ManagerMessage) GetStopTail() *StopTail {
	if x != nil {
		if x, ok := x.Msg.(*ManagerMessage_StopTail); ok {
			return x.StopTail
		}
	}
	return nil
}

func (x *ManagerMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Msg.(*ManagerMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isManagerMessage_Msg interface {
	isManagerMessage_Msg()
}

type ManagerMessage_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,2,opt,name=welcome,proto3,oneof"`
}

type ManagerMessage_Apply struct {
	Apply *Apply `protobuf:"bytes,3,opt,name=apply,proto3,oneof"`
}

type ManagerMessage_Restart struct {
	Restart *Restart `protobuf:"bytes,4,opt,name=restart,proto3,oneof"`
}

type ManagerMessage_StartTail struct {
	StartTail *StartTail `protobuf:"bytes,5,opt,name=start_tail,json=startTail,proto3,oneof"`
}

type ManagerMessage_StopTail struct {
	StopTail *StopTail `protobuf:"bytes,6,opt,name=stop_tail,json=stopTail,proto3,oneof"`
}

type ManagerMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,7,opt,name=ping,proto3,oneof"`
}

func (*ManagerMessage_Welcome) isManagerMessage_Msg() {}

func (*ManagerMessage_Apply) isManagerMessage_Msg() {}

func (*ManagerMessage_Restart) isManagerMessage_Msg() {}

func (*ManagerMessage_StartTail) isManagerMessage_Msg() {}

func (*ManagerMessage_StopTail) isManagerMessage_Msg() {}

func (*ManagerMessage_Ping) isManagerMessage_Msg() {}

type Welcome struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// How often the agent should send Status while nothing changes.
	StatusIntervalSeconds uint32 `protobuf:"varint,1,opt,name=status_interval_seconds,json=statusIntervalSeconds,proto3" json:"status_interval_seconds,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Welcome) GetStatusIntervalSeconds() uint32 {
	if x != nil {
		return x.StatusIntervalSeconds
	}
	return 0
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *File) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *File) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

// Apply replaces the whole configuration. The agent validates it, switches to it and reloads
// the proxy; when any step fails it restores the previous configuration and reports an error.
type Apply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Paths relative to the configuration root.
	Files    map[string]*File `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Checksum string           `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	// Traefik's API entrypoint on 127.0.0.1, used to check for configuration errors.
	AdminPort     uint32 `protobuf:"varint,3,opt,name=admin_port,json=adminPort,proto3" json:"admin_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Apply) Reset() {
	*x = Apply{}
	mi := &file_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Apply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Apply) ProtoMessage() {}

func (x *Apply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Apply.ProtoReflect.Descriptor instead.
func (*Apply) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *Apply) GetFiles() map[string]*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *Apply) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *Apply) GetAdminPort() uint32 {
	if x != nil {
		return x.AdminPort
	}
	return 0
}

// Restart restarts the proxy process inside the container.
type Restart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Restart) Reset() {
	*x = Restart{}
	mi := &file_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Restart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Restart) ProtoMessage() {}

func (x *Restart) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Restart.ProtoReflect.Descriptor instead.
func (*Restart) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{6}
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{7}
}

// StartTail follows the access logs; lines arrive as LogChunk messages with the same stream_id.
type StartTail struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	StreamId string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	// Number of existing lines to send first.
	Lines         int32 `protobuf:"varint,2,opt,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTail) Reset() {
	*x = StartTail{}
	mi := &file_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTail) ProtoMessage() {}

func (x *StartTail) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTail.ProtoReflect.Descriptor instead.
func (*StartTail) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *StartTail) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *StartTail) GetLines() int32 {
	if x != nil {
		return x.Lines
	}
	return 0
}

type StopTail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTail) Reset() {
	*x = StopTail{}
	mi := &file_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTail) ProtoMessage() {}

func (x *StopTail) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTail.ProtoReflect.Descriptor instead.
func (*StopTail) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *StopTail) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type Result struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Ok        bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error     string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Validator or reload output, shown in the deploy log.
	Output        string `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *Result) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Result) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Result) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type Status struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ProxyRunning bool                   `protobuf:"varint,1,opt,name=proxy_running,json=proxyRunning,proto3" json:"proxy_running,omitempty"`
	// Unix seconds; 0 when the proxy is not running.
	ProxyStartedAt int64  `protobuf:"varint,2,opt,name=proxy_started_at,json=proxyStartedAt,proto3" json:"proxy_started_at,omitempty"`
	Restarts       uint32 `protobuf:"varint,3,opt,name=restarts,proto3" json:"restarts,omitempty"`
	ConfigChecksum string `protobuf:"bytes,4,opt,name=config_checksum,json=configChecksum,proto3" json:"config_checksum,omitempty"`
	LastError      string `protobuf:"bytes,5,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *Status) GetProxyRunning() bool {
	if x != nil {
		return x.ProxyRunning
	}
	return false
}

func (x *Status) GetProxyStartedAt() int64 {
	if x != nil {
		return x.ProxyStartedAt
	}
	return 0
}

func (x *Status) GetRestarts() uint32 {
	if x != nil {
		return x.Restarts
	}
	return 0
}

func (x *Status) GetConfigChecksum() string {
	if x != nil {
		return x.ConfigChecksum
	}
	return ""
}

func (x *Status) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type LogChunk struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	StreamId string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Lines    []*LogLine             `protobuf:"bytes,2,rep,name=lines,proto3" json:"lines,omitempty"`
	// The tail ended; error explains why when it was not stopped by the manager.
	Closed        bool   `protobuf:"varint,3,opt,name=closed,proto3" json:"closed,omitempty"`
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *LogChunk) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *LogChunk) GetLines() []*LogLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *LogChunk) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

func (x *LogChunk) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LogLine struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Log file name, e.g. "3.log" for nginx host 3 or "access.log" for Traefik.
	Source        string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Text          string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *LogLine) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogLine) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_v1_agent_proto protoreflect.FileDescriptor

const file_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x0ev1/agent.proto\x12\rproxyagent.v1\"\xd2\x01\n" +
	"\fAgentMessage\x12,\n" +
	"\x05hello\x18\x01 \x01(\v2\x14.proxyagent.v1.HelloH\x00R\x05hello\x12/\n" +
	"\x06result\x18\x02 \x01(\v2\x15.proxyagent.v1.ResultH\x00R\x06result\x12/\n" +
	"\x06status\x18\x03 \x01(\v2\x15.proxyagent.v1.StatusH\x00R\x06status\x12+\n" +
	"\x03log\x18\x04 \x01(\v2\x17.proxyagent.v1.LogChunkH\x00R\x03logB\x05\n" +
	"\x03msg\"\xaf\x01\n" +
	"\x05Hello\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\x04R\n" +
	"instanceId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x12#\n" +
	"\rproxy_version\x18\x04 \x01(\tR\fproxyVersion\x12'\n" +
	"\x0fconfig_checksum\x18\x05 \x01(\tR\x0econfigChecksum\"\xea\x02\n" +
	"\x0eManagerMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x122\n" +
	"\awelcome\x18\x02 \x01(\v2\x16.proxyagent.v1.WelcomeH\x00R\awelcome\x12,\n" +
	"\x05apply\x18\x03 \x01(\v2\x14.proxyagent.v1.ApplyH\x00R\x05apply\x122\n" +
	"\arestart\x18\x04 \x01(\v2\x16.proxyagent.v1.RestartH\x00R\arestart\x129\n" +
	"\n" +
	"start_tail\x18\x05 \x01(\v2\x18.proxyagent.v1.StartTailH\x00R\tstartTail\x126\n" +
	"\tstop_tail\x18\x06 \x01(\v2\x17.proxyagent.v1.StopTailH\x00R\bstopTail\x12)\n" +
	"\x04ping\x18\a \x01(\v2\x13.proxyagent.v1.PingH\x00R\x04pingB\x05\n" +
	"\x03msg\"A\n" +
	"\aWelcome\x126\n" +
	"\x17status_interval_seconds\x18\x01 \x01(\rR\x15statusIntervalSeconds\"4\n" +
	"\x04File\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\"\xc8\x01\n" +
	"\x05Apply\x125\n" +
	"\x05files\x18\x01 \x03(\v2\x1f.proxyagent.v1.Apply.FilesEntryR\x05files\x12\x1a\n" +
	"\bchecksum\x18\x02 \x01(\tR\bchecksum\x12\x1d\n" +
	"\n" +
	"admin_port\x18\x03 \x01(\rR\tadminPort\x1aM\n" +
	"\n" +
	"FilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.proxyagent.v1.FileR\x05value:\x028\x01\"\t\n" +
	"\aRestart\"\x06\n" +
	"\x04Ping\">\n" +
	"\tStartTail\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x14\n" +
	"\x05lines\x18\x02 \x01(\x05R\x05lines\"'\n" +
	"\bStopTail\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\"e\n" +
	"\x06Result\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\"\xbb\x01\n" +
	"\x06Status\x12#\n" +
	"\rproxy_running\x18\x01 \x01(\bR\fproxyRunning\x12(\n" +
	"\x10proxy_started_at\x18\x02 \x01(\x03R\x0eproxyStartedAt\x12\x1a\n" +
	"\brestarts\x18\x03 \x01(\rR\brestarts\x12'\n" +
	"\x0fconfig_checksum\x18\x04 \x01(\tR\x0econfigChecksum\x12\x1d\n" +
	"\n" +
	"last_error\x18\x05 \x01(\tR\tlastError\"\x83\x01\n" +
	"\bLogChunk\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12,\n" +
	"\x05lines\x18\x02 \x03(\v2\x16.proxyagent.v1.LogLineR\x05lines\x12\x16\n" +
	"\x06closed\x18\x03 \x01(\bR\x06closed\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"5\n" +
	"\aLogLine\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text2W\n" +
	"\n" +
	"ProxyAgent\x12I\n" +
	"\aConnect\x12\x1b.proxyagent.v1.AgentMessage\x1a\x1d.proxyagent.v1.ManagerMessage(\x010\x01B?Z=github.com/supabase-manager/shared/proxyagent/v1;proxyagentv1b\x06proto3"

var (
	file_v1_agent_proto_rawDescOnce sync.Once
	file_v1_agent_proto_rawDescData []byte
)

func file_v1_agent_proto_rawDescGZIP() []byte {
	file_v1_agent_proto_rawDescOnce.Do(func() {
		file_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_agent_proto_rawDesc), len(file_v1_agent_proto_rawDesc)))
	})
	return file_v1_agent_proto_rawDescData
}

var file_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_v1_agent_proto_goTypes = []any{
	(*AgentMessage)(nil),   // 0: proxyagent.v1.AgentMessage
	(*Hello)(nil),          // 1: proxyagent.v1.Hello
	(*ManagerMessage)(nil), // 2: proxyagent.v1.ManagerMessage
	(*Welcome)(nil),        // 3: proxyagent.v1.Welcome
	(*File)(nil),           // 4: proxyagent.v1.File
	(*Apply)(nil),          // 5: proxyagent.v1.Apply
	(*Restart)(nil),        // 6: proxyagent.v1.Restart
	(*Ping)(nil),           // 7: proxyagent.v1.Ping
	(*StartTail)(nil),      // 8: proxyagent.v1.StartTail
	(*StopTail)(nil),       // 9: proxyagent.v1.StopTail
	(*Result)(nil),         // 10: proxyagent.v1.Result
	(*Status)(nil),         // 11: proxyagent.v1.Status
	(*LogChunk)(nil),       // 12: proxyagent.v1.LogChunk
	(*LogLine)(nil),        // 13: proxyagent.v1.LogLine
	nil,                    // 14: proxyagent.v1.Apply.FilesEntry
}
var file_v1_agent_proto_depIdxs = []int32{
	1,  // 0: proxyagent.v1.AgentMessage.hello:type_name -> proxyagent.v1.Hello
	10, // 1: proxyagent.v1.AgentMessage.result:type_name -> proxyagent.v1.Result
	11, // 2: proxyagent.v1.AgentMessage.status:type_name -> proxyagent.v1.Status
	12, // 3: proxyagent.v1.AgentMessage.log:type_name -> proxyagent.v1.LogChunk
	3,  // 4: proxyagent.v1.ManagerMessage.welcome:type_name -> proxyagent.v1.Welcome
	5,  // 5: proxyagent.v1.ManagerMessage.apply:type_name -> proxyagent.v1.Apply
	6,  // 6: proxyagent.v1.ManagerMessage.restart:type_name -> proxyagent.v1.Restart
	8,  // 7: proxyagent.v1.ManagerMessage.start_tail:type_name -> proxyagent.v1.StartTail
	9,  // 8: proxyagent.v1.ManagerMessage.stop_tail:type_name -> proxyagent.v1.StopTail
	7,  // 9: proxyagent.v1.ManagerMessage.ping:type_name -> proxyagent.v1.Ping
	14, // 10: proxyagent.v1.Apply.files:type_name -> proxyagent.v1.Apply.FilesEntry
	13, // 11: proxyagent.v1.LogChunk.lines:type_name -> proxyagent.v1.LogLine
	4,  // 12: proxyagent.v1.Apply.FilesEntry.value:type_name -> proxyagent.v1.File
	0,  // 13: proxyagent.v1.ProxyAgent.Connect:input_type -> proxyagent.v1.AgentMessage
	2,  // 14: proxyagent.v1.ProxyAgent.Connect:output_type -> proxyagent.v1.ManagerMessage
	14, // [14:15] is the sub-list for method output_type
	13, // [13:14] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_v1_agent_proto_init() }
func file_v1_agent_proto_init() {
	if File_v1_agent_proto != nil {
		return
	}
	file_v1_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Hello)(nil),
		(*AgentMessage_Result)(nil),
		(*AgentMessage_Status)(nil),
		(*AgentMessage_Log)(nil),
	}
	file_v1_agent_proto_msgTypes[2].OneofWrappers = []any{
		(*ManagerMessage_Welcome)(nil),
		(*ManagerMessage_Apply)(nil),
		(*ManagerMessage_Restart)(nil),
		(*ManagerMessage_StartTail)(nil),
		(*ManagerMessage_StopTail)(nil),
		(*ManagerMessage_Ping)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_agent_proto_rawDesc), len(file_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_agent_proto_goTypes,
		DependencyIndexes: file_v1_agent_proto_depIdxs,
		MessageInfos:      file_v1_agent_proto_msgTypes,
	}.Build()
	File_v1_agent_proto = out.File
	file_v1_agent_proto_goTypes = nil
	file_v1_agent_proto_depIdxs = nil
}
