// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: v1/agent.proto

package proxyagentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProxyAgent_Connect_FullMethodName = "/proxyagent.v1.ProxyAgent/Connect"
)

// ProxyAgentClient is the client API for ProxyAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProxyAgent connects a proxy container's agent with the manager.
//
// The agent dials the manager and keeps one Connect stream open, so agents can run behind NAT
// or on other hosts. It authenticates with gRPC metadata: "authorization: Bearer <token>" and
// "x-sm-instance: <instance id>". The first message on the stream is Hello; the manager answers
// with Welcome. After that the manager sends commands and the agent answers each with a Result
// carrying the same request_id, and pushes Status and LogChunk messages on its own.
type ProxyAgentClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ManagerMessage], error)
}

type proxyAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewProxyAgentClient(cc grpc.ClientConnInterface) ProxyAgentClient {
	return &proxyAgentClient{cc}
}

func (c *proxyAgentClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ManagerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProxyAgent_ServiceDesc.Streams[0], ProxyAgent_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, ManagerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProxyAgent_ConnectClient = grpc.BidiStreamingClient[AgentMessage, ManagerMessage]

// ProxyAgentServer is the server API for ProxyAgent service.
// All implementations must embed UnimplementedProxyAgentServer
// for forward compatibility.
//
// ProxyAgent connects a proxy container's agent with the manager.
//
// The agent dials the manager and keeps one Connect stream open, so agents can run behind NAT
// or on other hosts. It authenticates with gRPC metadata: "authorization: Bearer <token>" and
// "x-sm-instance: <instance id>". The first message on the stream is Hello; the manager answers
// with Welcome. After that the manager sends commands and the agent answers each with a Result
// carrying the same request_id, and pushes Status and LogChunk messages on its own.
type ProxyAgentServer interface {
	Connect(grpc.BidiStreamingServer[AgentMessage, ManagerMessage]) error
	mustEmbedUnimplementedProxyAgentServer()
}

// UnimplementedProxyAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProxyAgentServer struct{}

func (UnimplementedProxyAgentServer) Connect(grpc.BidiStreamingServer[AgentMessage, ManagerMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedProxyAgentServer) mustEmbedUnimplementedProxyAgentServer() {}
func (UnimplementedProxyAgentServer) testEmbeddedByValue()                    {}

// UnsafeProxyAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProxyAgentServer will
// result in compilation errors.
type UnsafeProxyAgentServer interface {
	mustEmbedUnimplementedProxyAgentServer()
}

func RegisterProxyAgentServer(s grpc.ServiceRegistrar, srv ProxyAgentServer) {
	// If the following call panics, it indicates UnimplementedProxyAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProxyAgent_ServiceDesc, srv)
}

func _ProxyAgent_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProxyAgentServer).Connect(&grpc.GenericServerStream[AgentMessage, ManagerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProxyAgent_ConnectServer = grpc.BidiStreamingServer[AgentMessage, ManagerMessage]

// ProxyAgent_ServiceDesc is the grpc.ServiceDesc for ProxyAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProxyAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proxyagent.v1.ProxyAgent",
	HandlerType: (*ProxyAgentServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _ProxyAgent_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "v1/agent.proto",
}
